aquasecurity/terraform-provider-aquasec

.github/workflows/test.yml, aquasec/data_users_test.go, aquasec/resource_user_test.go, examples/data-sources/main.tf, examples/provider/provider.tf, examples/resources/main.tf, go.mod, go.sum
Will need to create three repository secrets that can communicate with Aqua
AQUA_URL
AQUA_USER
AQUA_PASSWORD
=> Working acceptance tests for user resource and data source

aquasec/provider.go, client/client.go, client/util.go, docs/index.md
Signed-off-by: Mohammad Fahim Abrar <fahimabrar02@gmail.com>
=> Add `AQUA_TLS_VERIFY` Environment Variable

.github/workflows/test.yml, client/enforcers.go, client/notifications.go, client/registries.go
Signed-off-by: Mohammad Fahim Abrar <fahimabrar02@gmail.com>
=> Avoid hardcoding `InsecureSkipVerify` as true

README.md, examples/data-sources/main.tf, examples/provider/provider.tf, examples/resources/main.tf
Fixing issue https://github.com/aquasecurity/terraform-provider-aquasec/issues/44
Updating readme
=> Fix provider definition in the examples

GNUmakefile, README.md, aquasec/provider.go, client/client.go
Closing #55 Added new variable in the provider configuration to support SaaS authentication and resource flow.
=> Changes for Issue #55

aquasec/data_gateway.go, aquasec/data_gateway_test.go, aquasec/provider.go, aquasec/utils.go, client/gateway.go, examples/data-sources/aquasec_gateways/data-source.tf, examples/data-sources/main.tf
=> added gateway as data source

DEVELOPMENT.md, GNUmakefile, README.md, aquasec/provider.go, client/client.go, docs/index.md, examples/data-sources/main.tf, examples/provider/provider.tf, examples/resources/main.tf
Fix authentication to SaaS
Tested on all aqua platforms with success
Fix #100
=> Fix authentication to Aqua SaaS and update version to 0.8.9

.github/workflows/test.yml
Updating Terraform versions matrix to:
'0.15.5'
'0.13.7'
'1.1.2'
Tested locally with success with act
=> Updating terraform versions matrix

aquasec/resource_application_scope.go, aquasec/resource_container_runtime_policy.go, aquasec/resource_container_runtime_policy_test.go, aquasec/resource_firewall_policy.go, aquasec/resource_function_assurance_policy.go, aquasec/resource_function_runtime_policy.go, aquasec/resource_group.go, aquasec/resource_host_assurance_policy.go, aquasec/resource_host_runtime_policy.go, aquasec/resource_image.go, aquasec/resource_image_assurance_policy.go, aquasec/resource_permission_set.go, aquasec/resource_role.go, aquasec/resource_service.go, aquasec/resource_user_saas.go
=> feat: adding forceNew for all resources IDs

aquasec/resource_application_scope_test.go, aquasec/resource_container_runtime_policy_test.go, aquasec/resource_enforcer_group_test.go, aquasec/resource_firewall_policy_test.go, aquasec/resource_function_assurance_policy_test.go, aquasec/resource_function_runtime_policy_test.go, aquasec/resource_host_assurance_policy_test.go, aquasec/resource_host_runtime_policy_test.go, aquasec/resource_image_assurance_policy_test.go, aquasec/resource_image_test.go, aquasec/resource_notification_test.go, aquasec/resource_registry_test.go, aquasec/resource_service_test.go, aquasec/utils_test.go
This will check resources are destroyed correctly on a terraform destroy
=> feat: adding CheckDestroy to all resources

aquasec/data_registry.go, aquasec/data_registry_test.go, aquasec/resource_image_test.go, aquasec/resource_registry.go, aquasec/resource_registry_test.go, aquasec/resource_user.go, client/client.go, client/registries.go, docs/resources/integration_registry.md, docs/resources/user.md
fix #152 
fix #164 
---
update docs
=> feat: add support to add specific scanner to registry create/update/delete

GNUmakefile, client/application_scope.go, client/assurance_policy.go, client/client.go, client/enforcers.go, client/firewall_policy.go, client/gateway.go, client/group.go, client/image.go, client/notifications.go, client/permission_sets.go, client/registries.go, client/role.go, client/runtime_policy.go, client/service.go, client/user.go, client/vulnerabilities.go, go.mod, go.sum
=> bug: fix client crushing when deploying many resources

aquasec/utils.go, client/client.go, client/group.go, client/user.go, consts/consts.go
=> feat: add support for new SaaS regions

aquasec/data_registry.go, aquasec/resource_registry.go, client/registries.go, docs/data-sources/integration_registries.md, docs/resources/integration_registry.md
=> feat: aquasec integration registry - add more controls

aquasec/data_host_runtime_policy.go, aquasec/resource_host_runtime_policy.go, client/runtime_policy.go, docs/data-sources/host_runtime_policy.md, docs/resources/host_runtime_policy.md
=> feat: Added support for Host Runtime Policy > Real-Time Malware Protection

aquasec/data_container_runtime_policy.go, aquasec/resource_container_runtime_policy.go, docs/data-sources/container_runtime_policy.md, docs/resources/container_runtime_policy.md, docs/resources/kubernetes_assurance_policy.md, examples/resources/aquasec_container_runtime_policy/resource.tf, examples/resources/main.tf
=> feat: add malware_scan_options to container_runtime_policy (Real-Time Malware Protection)

aquasec/data_registry.go, aquasec/resource_registry.go, client/registries.go, docs/data-sources/integration_registries.md, docs/resources/container_runtime_policy.md, docs/resources/function_runtime_policy.md, docs/resources/host_runtime_policy.md, docs/resources/integration_registry.md
=> feat: add auto_cleanup to registry resource

aquasec/data_registry.go, aquasec/resource_registry.go, aquasec/resource_registry_test.go
Adding description to the scheme
fix: #212
=> bug: missing description in aquasec_integration_registry.

aquasec/resource_application_scope.go, aquasec/resource_application_scope_test.go, docs/data-sources/integration_registries.md, docs/resources/application_scope.md, docs/resources/integration_registry.md
Adding set for categories in read operation
Fix #224
=> bug: Fixing application scope drift detection.

aquasec/resource_role_mapping_sass.go, client/sso.go
Error: error calling /v2/samlmappings, error: {"status":422,"code":1,"message":"Invalid request","errors":[{"field":"data","message":"has additional properties","value":"data.email","type":"object","schemaPath":[]},{"field":"data","message":"has additional properties","value":"data.password","type":"object","schemaPath":[]}]}
=> bug: fixing aquasec_role_mapping_saas issue

GNUmakefile, aquasec/resource_container_runtime_policy.go, aquasec/resource_permission_set.go, aquasec/resource_role.go, client/group.go, client/ldap.go, client/role.go, client/sso.go, docs/resources/permissions_sets.md, docs/resources/role.md, examples/resources/aquasec_permissions_sets/resource.tf
+ Docs updated 
+ Example updated
Fix #240
=> Permission_set & Role aligned with API, Client usage extended to additional resources

DEVELOPMENT.md, GNUmakefile, README.md, aquasec/data_registry.go, aquasec/resource_registry.go, client/registries.go, docs/data-sources/integration_registries.md, docs/index.md, docs/resources/integration_registry.md, docs/resources/permissions_sets.md, examples/data-sources/main.tf, examples/provider/provider.tf, examples/resources/aquasec_integration_registry/resource.tf, examples/resources/main.tf
=> fix: registry_integration and readme files

aquasec/data_registry.go, aquasec/resource_registry.go, docs/data-sources/integration_registries.md, docs/resources/integration_registry.md
Resolves: https://github.com/aquasecurity/terraform-provider-aquasec/issues/247
=> doc: adding GAR type to registry integration

aquasec/data_service.go, aquasec/resource_service.go, client/service.go, docs/data-sources/service.md, docs/resources/service.md, examples/resources/aquasec_service/resource.tf
added optional "resource" field for being able to add custom CIDR's
Resolves: SLK-90014
=> Fix firewall settings for Aqua Services

DEVELOPMENT.md, GNUmakefile, README.md, docs/index.md, examples/data-sources/main.tf, examples/provider/provider.tf, examples/resources/main.tf
- Update Aquasec provider from 0.8.33 to 0.8.34
=> chore(terraform): update provider version to 0.8.34

aquasec/data_host_runtime_policy_test.go, aquasec/resource_host_runtime_policy_test.go, examples/resources/aquasec_host_runtime_policy/resource.tf
Resolves: SAAS-28331-aquasec-host-runtime-policy
=> refactor: aquasec host runtime policy(SAAS-28331)

aquasec/resource_role.go
=> bug: aquasec role - fix deletion

.gitignore, DEVELOPMENT.md, GNUmakefile, README.md, aquasec/data_users_saas.go, aquasec/resource_user_saas.go, aquasec/resource_user_saas_test.go, aquasec/utils.go, client/user.go, docs/index.md, examples/data-sources/main.tf, examples/provider/provider.tf, examples/resources/aquasec_user_saas/resource.tf, examples/resources/main.tf
* Modify terraform schema definition for user saas to include mfa_enabled field.
* Update the terraform aquasec_user_saas example Resolves: SAAS-29596
=> Fix for error during SaaS user creation

DEVELOPMENT.md, GNUmakefile, README.md, docs/index.md, examples/data-sources/main.tf, examples/provider/provider.tf, examples/resources/main.tf
* Documentation update for integration registry
=> rel: Release of 0.8.40

.github/workflows/nightly.yml, examples/main.tf
implementation:
- Fix the variable names in the GitHub Actions workflow file to match those defined in variables.tf
- Updated night workflow to save the plan to a binary file _ Updated main.tf to fix the issue which was observed during the terraform plan execution
=> bug: TP | night regression failure

aquasec/data_acknowledge.go, aquasec/resource_acknowledge.go, aquasec/resource_acknowledge_test.go, client/acknowledge.go, docs/data-sources/acknowledges.md, docs/resources/acknowledge.md, docs/resources/enforcer_groups.md, docs/resources/image.md
implementation:
* Added new fields to Acknowledge struct in client/acknowledge.go
* Updated resource schema in aquasec/resource_acknowledge.go and aquasec/data_acknowledge.go
* Modified create and read functions to handle new fields
* Updated examples and documentation to reflect changes
jira:
[SLK-102611](https://scalock.atlassian.net/browse/SLK-102611): TP | Add a new resource for Vulnerability Acknowledgements
=> feat: added new fields to support suppression rules in acknowledge resource and data source
